#!groovy


pipeline {
    agent { docker 'maven:3.3.3' }


    stages {
        stage('build') {
            steps {
                sh 'mvn --version'

                sh '''
                                   echo "Multiline shell steps works too"
                                   ls -lah
                               '''
            }
        }

        stage('deploy') {

            steps {
                timeout(time: 3, unit: 'MINUTES') {
                    echo 'Ha, I left you waiting!'
                }
            }
        }
    }

    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'Success!'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}